### PR TITLE
Revert seeds

### PR DESCRIPTION
**Pull request by Th3Whit3Wolf**
Fixes seeds

### CODE REVIEW

**Comment by tkbdsi** [comment]
Lol, those moments when there are 120k+ deletions and insertions

**Comment by Th3Whit3Wolf** [comment]
This nearly killed me lol

**Comment by tkbdsi** [comment]
Not gonna lie, you had that look of brain fatigue. 

(Sending these via mobile near a toddler so if there are typos you'll know why)

**Comment by tkbdsi** [comment]
Appreciate the work on fixing it though!

**Comment by Th3Whit3Wolf** [comment]
I definitely do.

**Pull request merged**
